import { format } from 'date-fns'

interface NotificationData {
  phoneNumber: string
  callerName?: string
  topic: string
  summary: string
  timestamp: string
}

export async function sendNotification(data: NotificationData): Promise<void> {
  const { phoneNumber, callerName, topic, summary, timestamp } = data

  const ownerWhatsApp = process.env.OWNER_WHATSAPP
  const ownerEmail = process.env.OWNER_EMAIL
  const ownerName = process.env.OWNER_NAME || 'Syed Eman Ali Shah'

  console.log('Sending notification for important call:', data)

  // Send WhatsApp notification
  if (ownerWhatsApp) {
    await sendWhatsAppMessage(ownerWhatsApp, {
      callerName: callerName || 'Unknown Caller',
      phoneNumber,
      topic,
      summary,
      timestamp
    })
  }

  // Send Email notification
  if (ownerEmail) {
    await sendEmailNotification(ownerEmail, {
      ownerName,
      callerName: callerName || 'Unknown Caller',
      phoneNumber,
      topic,
      summary,
      timestamp
    })
  }
}

async function sendWhatsAppMessage(
  recipientNumber: string,
  data: {
    callerName: string
    phoneNumber: string
    topic: string
    summary: string
    timestamp: string
  }
): Promise<void> {
  try {
    const accountSid = process.env.TWILIO_ACCOUNT_SID
    const authToken = process.env.TWILIO_AUTH_TOKEN
    const twilioWhatsApp = process.env.TWILIO_WHATSAPP_NUMBER || 'whatsapp:+14155238886'

    if (!accountSid || !authToken) {
      console.log('Twilio credentials not configured for WhatsApp')
      return
    }

    const message = `🔔 *Important Call Alert*

📞 *Caller:* ${data.callerName}
📱 *Phone:* ${data.phoneNumber}
📋 *Topic:* ${data.topic}
🕐 *Time:* ${format(new Date(data.timestamp), 'MMM d, yyyy • h:mm a')}

💬 *Summary:*
${data.summary}

---
Handled by Iqra AI Assistant`

    // In production, use Twilio WhatsApp API
    const client = require('twilio')(accountSid, authToken)

    await client.messages.create({
      from: twilioWhatsApp,
      to: `whatsapp:${recipientNumber}`,
      body: message
    })

    console.log('WhatsApp notification sent successfully')
  } catch (error) {
    console.error('Error sending WhatsApp message:', error)
  }
}

async function sendEmailNotification(
  recipientEmail: string,
  data: {
    ownerName: string
    callerName: string
    phoneNumber: string
    topic: string
    summary: string
    timestamp: string
  }
): Promise<void> {
  try {
    // In production, use SendGrid, AWS SES, or other email service
    // For now, we'll log the email content

    const emailHTML = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .info-row { margin: 15px 0; }
    .label { font-weight: bold; color: #667eea; }
    .summary { background: white; padding: 15px; border-left: 4px solid #667eea; margin: 20px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📞 Important Call Alert</h1>
      <p>Dear ${data.ownerName},</p>
      <p>Iqra has handled an important call that requires your attention.</p>
    </div>
    <div class="content">
      <div class="info-row">
        <span class="label">Caller:</span> ${data.callerName}
      </div>
      <div class="info-row">
        <span class="label">Phone Number:</span> ${data.phoneNumber}
      </div>
      <div class="info-row">
        <span class="label">Topic:</span> ${data.topic}
      </div>
      <div class="info-row">
        <span class="label">Time:</span> ${format(new Date(data.timestamp), 'MMMM d, yyyy • h:mm a')}
      </div>
      <div class="summary">
        <div class="label">Call Summary:</div>
        <p>${data.summary}</p>
      </div>
      <p style="margin-top: 30px;">
        Please review this call and respond to the caller at your earliest convenience.
      </p>
    </div>
    <div class="footer">
      <p>This notification was automatically generated by Iqra AI Assistant</p>
      <p>Powered by AI Voice Technology</p>
    </div>
  </div>
</body>
</html>
    `

    // Log email content (in production, send via email service)
    console.log('Email notification prepared for:', recipientEmail)
    console.log('Subject: Important Call Alert - ', data.callerName)
    console.log('Email HTML ready to send')

    // Example with a generic email service:
    // await emailService.send({
    //   to: recipientEmail,
    //   subject: `Important Call Alert - ${data.callerName}`,
    //   html: emailHTML
    // })

  } catch (error) {
    console.error('Error sending email notification:', error)
  }
}

export async function sendTestNotification(): Promise<void> {
  await sendNotification({
    phoneNumber: '+1234567890',
    callerName: 'Test Caller',
    topic: 'Test Call',
    summary: 'This is a test notification from Iqra AI Assistant',
    timestamp: new Date().toISOString()
  })
}
